### ISSUE TITLE
Extra overlays for BeagleBone Blue

### ISSUE THREAD

**Issue by jadonk** [beagleboard/bb.org-overlays#128]
https://gist.github.com/jadonk/16e92e1498d8acecd8df342e0b34719c 
https://gist.github.com/jadonk/bcc5f1e65f39406800c3c32cb81290b1 
https://gist.github.com/jadonk/b71edbb4309a50fd91798b736c6fad85 

Possibly more coming soon. Adding issue to track to closure.

**Comment by RobertCNelson** [comment]
merged thanks!
