### ISSUE TITLE
Linux beaglebone 4.14.108-ti-r108

### ISSUE THREAD

**Issue by comarius** [beagleboard/bb.org-overlays#140]
Hi 
On BBB
    ###Cape Universal Enable
    enable_uboot_cape_universal=1

Hello,

- I can see in this kernel the pwm's being enabled, and the naming is pwm-0:0.Is the first digit the chip then second the export # always. ?
- Is there a way to find out from the sys file system the pwm-0:0   GPIO kernel # or the rail PX_Y pin association. Thank you.

    lrwxrwxrwx 1 root pwm    0 Oct 11 19:42 device -> ../../../48300100.ecap
    --w--w---- 1 root pwm 4096 Oct 11 19:42 export
    -r--r--r-- 1 root pwm 4096 Oct 11 19:41 npwm
    drwxrwxr-x 2 root pwm    0 Oct 11 19:41 power
    drwxrwxr-x 3 root pwm    0 Oct 11 19:41 pwm-0:0

Also some pins mapping from config-pin does not apply. On th eold kernel I was able to 
use GPIO 71  P8-46  on pwmchip6/pwm1  but now exporting 1 > gpiochip6 says no device.
I wrote this https://redypis.org/addons/bb_pins.php  utility to parse the config_pin array and I see
that p8_46 is on  0x3:ehrpwm2B which is EHRPWM2 (ePWM2) which is pwmchip6 channel B
so export 1 should work !
What I am missing. Thank you

    beaglebone:/sys/class/pwm/pwmchip6$ echo 1 > export 
    -bash: echo: write error: No such device

And then all these fail

`
user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ echo 10000 > ./duty_cycle 
	-bash: echo: write error: Invalid argument
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ echo 1 > enable 
	-bash: echo: write error: Invalid argument
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ echo 0 > enable 
	-bash: echo: write error: Invalid argument
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ config-pin P8.46 pwm
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ echo 1 > enable 
	-bash: echo: write error: Invalid argument
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ echo 0 > enable 
	-bash: echo: write error: Invalid argument
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ echo 0 > ./enable 
	-bash: echo: write error: Invalid argument
	user@beaglebone:/sys/class/pwm/pwmchip6/pwm-6:0$ 
`

**Comment by RobertCNelson** [comment]
Repeat of: https://github.com/beagleboard/bb.org-overlays/issues/139 closing
