### ISSUE TITLE
BB-SPIDEV1A1-00A0 invalid, let's nuke it..

### ISSUE THREAD

**Issue by RobertCNelson** [beagleboard/bb.org-overlays#159]
has anyone tested SPIDEV1A, the alt version one? I can't get the pinmux tool to enable SPI1_SCLK on C18 (P9.42) with SPI1_D0 on B13 (P9.29) and SPI1_D1 on D12 (P9.30).

I checked the pnmux on the first two in my exercise of trying to finalize https://elinux.org/Beagleboard:BeagleBone_cape_interface_spec

there is a SPI1_SCLK on that pin, but the other pins aren't available.

**Comment by mvduin** [comment]
This pinout is perfectly valid.  If the pinmux tool has an issue with it, that's a bug in the pinmux tool.

**Comment by mvduin** [comment]
never mind, I misread what it says
