### ISSUE TITLE
Where can I find overlays for the 3.8.x Linux kernel?

### ISSUE THREAD

**Issue by spmaniato** [beagleboard/bb.org-overlays#21]
I'm guessing that the `dts` files under `src/arm` are designed for the `4.1.x` and `4.4.x` kernels, right?

I had to downgrade my kernel to `3.8.13` due to RobertCNelson/bb.org-overlays#4 and I was wondering where I could find the `dts` files for `3.8.x`. Thank you :smile:

**Comment by RobertCNelson** [comment]
https://github.com/beagleboard/linux/tree/3.8/firmware/capes

**Comment by spmaniato** [comment]
Perfect, thanks!
