### ISSUE TITLE
Analog inputs, header pins, and channel numbers

### ISSUE THREAD

**Issue by fivdi** [beagleboard/bb.org-overlays#5]
I'm currently testing analog inputs on a BeagleBone Black with [BB-ADC-00A0.dts](https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BB-ADC-00A0.dts). The OS image being used is bone-debian-8.1-lxqt-4gb-armhf-2015-07-05-4gb.img.xz form [here](https://rcn-ee.com/rootfs/bb.org/testing/2015-07-05/lxqt-4gb/).

`uname -a` outputs:
```
Linux beaglebone 4.1.1-bone9 #1 Tue Jun 30 06:09:30 UTC 2015 armv7l GNU/Linux
```
Assuming the analog inputs image below is correct, then `P9.39` should be reserved for `AIN0` [here](https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BB-ADC-00A0.dts#L21), not `P9.31`.

Also, the channel numbers 1 through 7 [here](https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BB-ADC-00A0.dts#L37) appear to be incorrect. I think channel numbers should be 0 through 6. For example, if overlay `BB-ADC-00A0.dts` is used and an analog sensor is connected to `AIN5 (P9.36)`, the raw value appears in `/sys/bus/iio/devices/iio:device0/in_voltage5_raw`, but I'd expect it to appear in `/sys/bus/iio/devices/iio:device0/in_voltage6_raw`. If the same analog sensor is connected to `AIN0 (P9.39)` the raw value doesn't appear in `/sys/bus/iio/devices/iio:device0/in_voltage1_raw`. Note that there is no file called `/sys/bus/iio/devices/iio:device0/in_voltage0_raw`.

If `P9.39` rather than `P9.31`is reserved for `AIN0` and the channel numbers are 0 through 6 rather than 1 through 7, everything functions as expected. The raw value for `AIN5` appears in `/sys/bus/iio/devices/iio:device0/in_voltage5_raw`, which is to be expected this time, and there is a file called `/sys/bus/iio/devices/iio:device0/in_voltage0_raw` for `AIN0` which is also to be expected.

The documentation [here](http://processors.wiki.ti.com/index.php/Linux_Core_ADC_User%27s_Guide) (if it's the correct documentation) also indicates that channel numbering starts at 0.
<img src="http://beagleboard.org/static/images/cape-headers-analog.png">

**Comment by RobertCNelson** [comment]
Thanks, should now be working as documented, i hadn't defined the ain0 node, quickly tested ain0->ain6 by shoring to p9_43 and reading the iio value to make sure it dropped to 0..

Regards,
