### ISSUE TITLE
request to add ETH WIZ click

### ISSUE THREAD

**Issue by easyw** [beagleboard/bb.org-overlays#52]
Hi,
would be possible to add this 10/100 BASE ethernet adapter?
https://shop.mikroe.com/eth-wiz-click
This is much better than the ETH Click which is a 10base adapter available as cape atm.

Thanks
Maurice

**Comment by RobertCNelson** [comment]
I see you forgot to attach your patch to update the wiznet driver to support device tree's..

Regards,

**Comment by easyw** [comment]
Hi Robert, 
unfortunately I don't have any patch... mine was just a request to eventually support this nice ethernet module for beagle bone ...
Thanks for considering that
Maurice

**Comment by RobertCNelson** [comment]
Well, this project is run by volunteers.  To speed up your request, you may have to do a little development.

Regards,

**Comment by RobertCNelson** [comment]
https://github.com/beagleboard/pocketbeagle/wiki/mikroBus%E2%84%A2-Click-Boards

merged

**Comment by easyw** [comment]
Thx 🥇
