### ISSUE TITLE
Pocket Beagle  SPI1 overlay mapping is not matching diagram

### ISSUE THREAD

**Issue by patrickpoirier51** [beagleboard/bb.org-overlays#54]
According to the diagram,  https://github.com/beagleboard/pocketbeagle/blob/master/docs/PocketBeagle_pinout.png
And to the PocketBeagle dts:
https://github.com/beagleboard/bb.org-overlays/blob/master/tools/pinmux-generator/PocketBeagle.dts#L564

There is a mismmatch in the universal cape : https://github.com/beagleboard/bb.org-overlays/blob/master/tools/beaglebone-universal-io/config-pin#L399

P2_25 (MOSI) should be defaulted to  spi1_d1 (not sp1_cs0):
P2_25_INFO="spi1_cs0 default gpio1_9 gpio1_9 gpio1_9 spi1_d1 spi1_cs0 uart4_txd dcan1_rx i2c1_scl"

Question about Chip Select:
Looking at BBB we have BOTH CS0 and CS1 on SPI1
https://github.com/beagleboard/bb.org-overlays/blob/master/tools/pinmux-generator/BeagleBone_Black.dts#L835

Would it be logical that we keep the same logic and have a spi1_cs0  on the PocketBeagle ?

**Comment by RobertCNelson** [comment]
Doh, then i messed up the commit message, yeah this is P2_25, it should be spi1_d1..
