### ISSUE TITLE
Cannot load the slots 7 and 8

### ISSUE THREAD

**Issue by sanjay265** [beagleboard/bb.org-overlays#60]
Hi

while I am trying to do dtos I cannot see all the slots loaded after exporting and doing " cat $SLOTS "
it shows till slots 4 and 5. And when i look into bone_capemgr.9 directory, I cannot see slots 7 and 8. By the way, I am using debian Image 7.8 on my beaglebone balck. Please help me, Im just a beginner.

debian@beaglebone:~$ export SLOTS=/sys/devices/bone_capemgr.9/slots
debian@beaglebone:~$ export PINS=/sys/kernel/debug/pinctrl/44e10800.pinmux/pins
debian@beaglebone:~$ nano ~/.profile
debian@beaglebone:~$ source ~/.profile
debian@beaglebone:~$ cat $SLOTS
 0: 54:PF--- 
 1: 55:PF--- 
 2: 56:PF--- 
 3: 57:PF--- 
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
debian@beaglebone:~$ cd /lib/firmware/
debian@beaglebone:/lib/firmware$ ls *SPI*
ADAFRUIT-SPI0-00A0.dtbo  ADAFRUIT-SPI1-00A0.dtbo
debian@beaglebone:/lib/firmware$ ls *UART*
ADAFRUIT-UART1-00A0.dtbo  ADAFRUIT-UART2-00A0.dtbo  ADAFRUIT-UART4-00A0.dtbo  ADAFRUIT-UART5-00A0.dtbo
debian@beaglebone:/lib/firmware$ cd /sys/devices/bone_capemgr.9/
debian@beaglebone:/sys/devices/bone_capemgr.9$ ls
baseboard  driver  modalias  power  slot-4  slot-5  slots  subsystem  uevent
debian@beaglebone:/sys/devices/bone_capemgr.9$ 
![github](https://user-images.githubusercontent.com/32374955/34230649-c0dbc7e4-e5a6-11e7-8a4e-14e8c1668f9d.png)

Thanks

**Comment by RobertCNelson** [comment]
@sanjay265 

3.8.x based kernels are not supported by this repo

kernel overlays are now considered EOL

For Support with this repo, please upgrade to v4.4.x and U-Boot Overlays

Otherwise, feel free to contact or search the archive on this mailing list: https://groups.google.com/forum/#!forum/beagleboard

Regards,

**Comment by sanjay265** [comment]
ok. 

thanks robert
