### ISSUE TITLE
dtc-overlay.sh: Unable to fetch git repo git://git.kernel.org

### ISSUE THREAD

**Issue by hypersolution1** [beagleboard/bb.org-overlays#7]
In dtc-overlay.sh, I renamed :
`server="git://git.kernel.org/pub/scm/utils/dtc"`
to:
`server="https://git.kernel.org/pub/scm/utils/dtc"`

to make it work.

**Comment by RobertCNelson** [comment]
Also fixes man in the middle attacks...
