### ISSUE TITLE
Please Clarify: what filesystem?

### ISSUE THREAD

**Issue by rkrehbiel** [beagleboard/bb.org-overlays#90]
I am configuring a microSD card for BeagleBone.  It must begin with a FAT filesystem in p1, because this allows the card to be inserted into a Windows PC for configuration chores.  It loads MLO/u-boot from FAT, then rootfs is p2 (ext4).  This card boots just fine, however, u-boot overlays do not seem to be working, and I suspect it's because I'm unclear on the filesystem from which the .dtbo are being loaded.  Is it p1 or p2?

**Comment by RobertCNelson** [comment]
Closing: User also posted on mailing list:

https://groups.google.com/forum/#!category-topic/beagleboard/hNTzn8g4_5g

Regards,
