### ISSUE TITLE
LCD Panel not working (LG4572B_DS)

### ISSUE THREAD

**Issue by debuggerpls** [beagleboard/bb.org-overlays#97]
Hello,
I am an intern and for the last week I cannot get LCD working. I am new and it seems that LCD worked on 4.1.x and before that on 3.x.x kernel. Now the kernel is 4.4.88-ti-r125 running with Ubuntu 16.04.
My question:
1. Are SGX drivers (pvrsrvkm, omaplfb) needed for displaying images with fbi on lcd? I have panel configured in overlay, but i get black screen that doesnt change.
2. Is it possible to install SGX drivers, because its ti-kernel and not bone, i tried https://elinux.org/BeagleBoardDebian#SGX_Drivers, but the drivers didnt get loaded.

Thank you

**Comment by RobertCNelson** [comment]
@debuggerpls it's probably a problem with your dts overlay, either compare your with the examples in this repo or post your lcd *.dts for comparison.

SGX drivers don't control the physical video output, they only deal with the framebuffer. Thus they aren't needed for normal video output.

Regards,
